# Generated by Django 4.2.2 on 2023-08-06 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='network.post'),
        ),
    ]
