# Generated by Django 4.2.2 on 2023-07-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bidding_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='lisitng_name',
            new_name='lisiting_name',
        ),
        migrations.AddField(
            model_name='bidding',
            name='bidded_by',
            field=models.CharField(default='Harry', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidding',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
