# Generated by Django 4.2.2 on 2023-07-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_image_url_alter_listing_listed_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='lisiting_name',
            new_name='listing_name',
        ),
    ]
