# Generated by Django 4.2.2 on 2023-07-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bidding_bidded_by_alter_bidding_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
    ]
