# Generated by Django 4.2.2 on 2023-07-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_is_active_alter_bidding_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
