# Generated by Django 4.2.2 on 2023-07-10 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bidding_bid_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bidded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='listing_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_on', to='auctions.listing'),
        ),
    ]
