# Generated by Django 4.2.2 on 2023-07-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_comment_commented_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='listing_name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='starting_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_price', to='auctions.bidding'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
