# Generated by Django 4.2.2 on 2023-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_bidding_listing_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bid',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='bidding',
            name='bid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
