# Generated by Django 4.2.2 on 2023-08-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
