# Generated by Django 4.2.2 on 2023-08-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyApps', '0002_user_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='question_anwer_pair',
            new_name='question_answer_pair',
        ),
    ]
