# Generated by Django 4.2.2 on 2023-08-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyApps', '0003_rename_question_anwer_pair_application_question_answer_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
