# Generated by Django 4.2.2 on 2023-08-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyApps', '0004_application_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
