# Generated by Django 4.2.2 on 2023-08-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyApps', '0005_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='military',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
